# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && sudo dpkg -i erlang-solutions_1.0_all.deb
    sudo apt-get update
    sudo apt-get install esl-erlang
    sudo apt-get install elixir
    mix local.hex
    elixir -v
  displayName: 'Install elixir and check version.'

- script: |
    sudo apt-get install nodejs
    node -v
    npm -v
  displayName: 'Install nodejs and check version.'

- script: |
    mix deps.get
    mix deps.compile
    mix test
  displayName: 'Compile elixir and run tests.'

- script: |
    cd assets && npm install
  displayName: 'Compile frontend and run tests.'
